feat(rule 1217): "Thread.run()" should not be called directly
SpoonLabs/sorald pull request #305
Opened 2021-01-02 22:04 UTC by khaes-kth

This processes [1217](https://rules.sonarsource.com/java/RSPEC-1217) warnings.

2021-01-05 12:53 UTC, slarse commented
Is this ready for review?

2021-01-05 13:31 UTC, slarse commented on src/main/java/sorald/processor/ThreadRunProcessor.java
> +    protected boolean canRepairInternal(CtInvocation candidate) {
```suggestion
    protected boolean canRepairInternal(CtInvocation<?> candidate) {
```

2021-01-05 13:32 UTC, slarse commented on src/main/java/sorald/processor/ThreadRunProcessor.java
> +        CtInvocation threadStartInvocation =
```suggestion
        CtInvocation<?> threadStartInvocation =
```

2021-01-07 06:59 UTC, slarse requested changes
Everything is here now, just have a couple of comments on the docs.

2021-01-07 06:59 UTC, slarse commented on docs/HANDLED_RULES.md
> +To get the expected behavior, call the Thread.start() method instead.
This is copied verbatim from https://rules.sonarsource.com/java/type/Bug/RSPEC-1217, which violates SonarSource's copyright of said material. Write what the processor does instead.

2021-01-07 06:59 UTC, slarse commented on docs/HANDLED_RULES.md
> ++   myThread.start(); // Compliant
Slightly misleading: the processor does not change the `// Noncompliant` comment to `// Compliant`. I'd personally just remove those comments as they might cause confusion.

2021-01-07 15:19 UTC, slarse approved these changes
LGTM, ready to merge?

2021-01-07 15:36 UTC, khaes-kth commented
> LGTM, ready to merge?

Yes!

2021-01-07 15:38 UTC, merged

2021-01-07 15:39 UTC, slarse commented
Nicely done! Your first merged processor, right? :tada:

2021-01-08 19:02 UTC, khaes-kth commented
> Nicely done! Your first merged processor, right?

As far as I remember :)