fix: Add exact-match search on variable name in joint declarations
SpoonLabs/sorald pull request #524
Opened 2021-05-11 09:08 UTC by slarse

Fix #522 

This PR extends the best fits scanner with a post filter that runs on all position-matched candidates. Currently, this post filter is only used to improve matching between rule violations and jointly declared variables.

@lyxell I know we discussed hamming distance, but I figured an exact match should be equally viable here. It may be that we find corner cases where the entire identifier can't be extracted, but I couldn't come up with one. Feel free to suggest more test cases and comment on the implementation!

2021-05-11 13:57 UTC, slarse commented
> Hopefully it should suffice to look for a comma as well?

Good catch! We can be super prudent and use [`Character.isJavaIdentifierPart`](https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html#isJavaIdentifierPart-char-) (which is slightly more permissive than [`Character.isJavaIdentifierStart`](https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html#isJavaIdentifierStart-char-) in allowing digits, but it should work fine).

2021-05-11 15:41 UTC, lyxell requested changes

2021-05-11 15:41 UTC, lyxell commented on src/main/java/sorald/sonar/BestFitScanner.java
> +        int symbolEndPos = reverseSearch(cuSource, searchStartPos, Character::isJavaIdentifierPart);
Maybe naming these `identifierStartPos` and `identifierEndPos` would be more intuitive?

2021-05-11 17:28 UTC, lyxell commented on src/main/java/sorald/sonar/BestFitScanner.java
> +    private static int reverseSearch(String s, int startIdx, Predicate<Character> predicate) {
I was just referring to the name of the method, I think using the predicate is a good idea.

2021-05-11 17:34 UTC, lyxell commented on src/main/java/sorald/sonar/BestFitScanner.java
> +        int symbolEndPos = reverseSearch(cuSource, searchStartPos, Character::isJavaIdentifierPart);
:+1:

2021-05-11 17:39 UTC, slarse commented on src/main/java/sorald/sonar/BestFitScanner.java
> +    private static int reverseSearch(String s, int startIdx, Predicate<Character> predicate) {
Oh, darn, I entirely misread your comment, now I totally see what you mean. The negation of the predicate is super confusing in combination with the method name. I don't find that nitpicking, that's just bad design (probably a product of my refactoring a loop out of the original method and not thinking twice).

Just a note: I might have understood what you meant if you'd commented on the entire method s.t. the negated predicate was actually in view (you can select multiple lines to comment by clicking-and-dragging in the margin).

2021-05-11 17:40 UTC, slarse commented on src/main/java/sorald/sonar/BestFitScanner.java
> +    private static int reverseSearch(String s, int startIdx, Predicate<Character> predicate) {
Or wait, am I just tired now? `while predicate is not true keep searching`? Does that not make sense?

2021-05-11 17:53 UTC, lyxell commented on src/main/java/sorald/sonar/BestFitScanner.java
> +    private static int reverseSearch(String s, int startIdx, Predicate<Character> predicate) {
Arguably, from reading the signature I still don't think it is entirely clear whether the method searches *until* the predicate holds or *while* the predicate holds, even though I would probably bet on the former. But if you think it's clear then it's all good.

2021-05-11 18:04 UTC, lyxell commented on src/main/java/sorald/sonar/BestFitScanner.java
> +    private static int reverseSearch(String s, int startIdx, Predicate<Character> predicate) {
I mean, I think it is already *kind of* clear, but I do think *reverseFind* would be even clearer.

2021-05-12 06:51 UTC, slarse commented
Codecov upload is currently failing. They'll probably sort it out during the day so I'll just wait a bit and re-run workflows after lunch.

@lyxell Thanks for the reviews, feel free to have a final look, I'll ping someone to merge when CI passes again.

2021-05-12 09:47 UTC, lyxell commented
Looks good to me!

2021-05-12 10:01 UTC, slarse commented
@fermadeiral Ready for merge.

2021-05-17 08:35 UTC, fermadeiral commented
Nice job! Thanks @slarse and @lyxell!

2021-05-17 08:36 UTC, merged